[package]
name = "idroid"
version = "0.2.4"
authors = ["li jinlei <grenlight@icloud.com>"]
edition = "2018"

[lib]
name = "idroid"
crate-type = ["rlib", "staticlib"]
# [target.'cfg(target_os = "android")'.lib]
# crate-type = ["cdylib"]

[features]
default = []

[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", version = "0.4", rev = "2003e6be1355a28ad9ba2eeb3238c06dfd24be22"  }
# wgpu = { path = "../../../wgpu-rs" }
uni-view = { path="../uni-view" }

nalgebra-glm = "*"
image = "0.23.2"
lazy_static = "*"
zerocopy = "0.3"
futures = "0.3"

[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
shaderc = "0.6.2"
objc = "*"
winit = "0.22"
raw-window-handle = "0.3"

[build-dependencies]
shaderc = "0.6.2"

