[package]
name = "idroid"
version = "0.2.5"
authors = ["li jinlei <grenlight@icloud.com>"]
edition = "2018"

[lib]
name = "idroid"
crate-type = ["rlib", "staticlib"]
# [target.'cfg(target_os = "android")'.lib]
# crate-type = ["cdylib"]

[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs",  version = "0.6", rev = "96b70210a87307158da37d0ee8ba69e47318aef8"  }
# wgpu = { path = "../../../wgpu-rs" }
uni-view = { path="../uni-view" }

nalgebra-glm = "*"
image = "0.23"
lazy_static = "*"
zerocopy = "0.3"
futures = "0.3"

[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
shaderc = { path="../../shaderc-rs/shaderc-rs" }
objc = "*"
winit = { version = "0.23", features = ["web-sys"] }
raw-window-handle = "0.3"

[build-dependencies]
shaderc = { path="../../shaderc-rs/shaderc-rs" }

