[package]
name = "idroid"
version = "0.2.6"
authors = ["li jinlei <grenlight@icloud.com>"]
edition = "2018"

[lib]
name = "idroid"
crate-type = ["rlib", "staticlib"]
# [target.'cfg(target_os = "android")'.lib]
# crate-type = ["cdylib"]

[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs",  version = "0.6", rev = "6af3f0f07ba06290c11e423807af5a8f62a07563"  }
# wgpu = { path = "../../../wgpu-rs" }
uni-view = { path="../uni-view" }

nalgebra-glm = "*"
image = "0.23"
lazy_static = "*"
zerocopy = "0.3"
futures = "0.3"

[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
shaderc = "0.7"
objc = "*"
winit = { version = "0.23.0", features = ["web-sys"] }
raw-window-handle = "0.3"

[build-dependencies]
shaderc = "0.7"

