[package]
name = "idroid"
version = "0.2.4"
authors = ["li jinlei <grenlight@icloud.com>"]
edition = "2018"

[lib]
name = "idroid"
crate-type = ["rlib", "staticlib"]
# [target.'cfg(target_os = "android")'.lib]
# crate-type = ["cdylib"]

[features]
default = []

[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs",  rev = "49640d2497ffac1936feb1cebb0ef64a39c31dce"  }
# wgpu = { path = "../../../wgpu-rs" }
uni-view = { path="../uni-view" }

nalgebra-glm = "*"
image = "0.23.2"
lazy_static = "*"
zerocopy = "0.3"
futures = "0.3"

[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
shaderc = "0.6.2"
objc = "*"
winit = { version = "0.22.1", features = ["web-sys"] }
raw-window-handle = "0.3"

[build-dependencies]
shaderc = "0.6.2"

