[package]
name = "idroid"
version = "0.2.5"
authors = ["li jinlei <grenlight@icloud.com>"]
edition = "2018"

[lib]
name = "idroid"
crate-type = ["rlib", "staticlib"]
# [target.'cfg(target_os = "android")'.lib]
# crate-type = ["cdylib"]

[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs",  version = "0.5", rev = "471d2a1a48c795a13d3c65a29ff184d7cfe9e766"  }
# wgpu = { path = "../../../wgpu-rs" }
uni-view = { path="../uni-view" }

nalgebra-glm = "*"
image = "0.23.6"
lazy_static = "*"
zerocopy = "0.3"
futures = "0.3"

[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
shaderc = { path="../../shaderc-rs/shaderc-rs" }
objc = "*"
winit = { version = "0.22.1", features = ["web-sys"] }
raw-window-handle = "0.3"

[build-dependencies]
shaderc = { path="../../shaderc-rs/shaderc-rs" }

