[package]
name = "uni-view"
version = "0.1.0"
authors = ["Li Jinlei <grenlight@icloud.com>"]


[dependencies]
libc = "*"
# wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "012d08d64de924da93289c2b51fb06b22d7348cf"  }
wgpu = { path = "../../../wgpu-rs" }

lazy_static = "*"

[target.'cfg(target_os = "macos")'.dependencies]
winit = "0.20.0-alpha4"
raw-window-handle = "0.3"

[target.wasm32-unknown-emscripten.dependencies]
stdweb =  "*"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "*"
objc-foundation = "*"
core-graphics = "*"

[target.'cfg(target_os = "android")'.dependencies]
log = "*"