[package]
name = "uni-view"
version = "0.2.5"
authors = ["Li Jinlei <grenlight@icloud.com>"]
edition = "2018"

[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", version = "0.5",  rev = "b0e1f055c693cee9075a04f007978ab9da1dc54b" }
# wgpu = { path = "../../../wgpu-rs" }

lazy_static = "*"
futures = "0.3"

[target.'cfg(target_os = "macos")'.dependencies]
winit = { version = "0.22.1", features = ["web-sys"] }
raw-window-handle = "0.3"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "*"
objc-foundation = "*"
core-graphics = "*"

[target.'cfg(target_os = "android")'.dependencies]
log = "*"