[package]
name = "uni-view"
version = "0.2.1"
authors = ["Li Jinlei <grenlight@icloud.com>"]


[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", version = "0.4", rev = "44fa1bc2fa208fa92f80944253e0da56cb7ac1fe"  }
# wgpu = { path = "../../../wgpu-rs" }

lazy_static = "*"

[target.'cfg(target_os = "macos")'.dependencies]
winit = "0.20.0-alpha4"
raw-window-handle = "0.3"

[target.wasm32-unknown-emscripten.dependencies]
stdweb =  "*"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "*"
objc-foundation = "*"
core-graphics = "*"

[target.'cfg(target_os = "android")'.dependencies]
log = "*"