[package]
name = "uni-view"
version = "0.2.4"
authors = ["Li Jinlei <grenlight@icloud.com>"]
edition = "2018"


[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs",  rev = "49640d2497ffac1936feb1cebb0ef64a39c31dce"  }
# wgpu = { path = "../../../wgpu-rs" }

lazy_static = "*"
futures = "0.3"

[target.'cfg(target_os = "macos")'.dependencies]
winit = { version = "0.22.1", features = ["web-sys"] }
raw-window-handle = "0.3"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "*"
objc-foundation = "*"
core-graphics = "*"

[target.'cfg(target_os = "android")'.dependencies]
log = "*"