[package]
name = "uni-view"
version = "0.2.3"
authors = ["Li Jinlei <grenlight@icloud.com>"]


[dependencies]
libc = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", version = "0.4", rev = "a96a5faa246c9f6643bf38557dc7206091d6f1e0"  }
# wgpu = { path = "../../../wgpu-rs" }

lazy_static = "*"

[target.'cfg(target_os = "macos")'.dependencies]
winit = "0.20"
raw-window-handle = "0.3"

[target.wasm32-unknown-emscripten.dependencies]
stdweb =  "*"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "*"
objc-foundation = "*"
core-graphics = "*"

[target.'cfg(target_os = "android")'.dependencies]
log = "*"